name: Build .NET MAUI Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Passe diese Version an deine installierte Version an

      - name: Install OpenJDK 17 (Android)
        run: brew install openjdk@17

      - name: Set up Java Environment
        run: |
          sudo ln -sfn /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk
          echo "JAVA_HOME=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home" >> $GITHUB_ENV

      - name: Restore .NET Workloads
        run: dotnet workload restore

      - name: Build Android App
        run: dotnet build --configuration Release -f net9.0-android

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore .NET Workloads
        run: dotnet workload restore

      - name: Build macOS App
        run: dotnet build --configuration Release -f net9.0-maccatalyst
